/*
 * Research projects — edit this list to add or update projects.
 *
 * Fields
 *   start / end : "YYYY/MM" (end may be "" for single-year NSTC grants)
 *   type        : "nstc"   = National Science and Technology Council (formerly MOST)
 *                 "agency" = commissioned by a government agency or company
 *   role        : "PI" or "Co-PI" (leave "" if not shown)
 *   region      : one of the keys in SITES (assets/data/sites.js), or "national"
 *   agency / title : { en: "...", zh: "..." }
 *
 * Newest first is not required — the page sorts by start date.
 */
window.PROJECTS = [
  /* ---------- Agency-commissioned projects ---------- */
  { type: "agency", start: "2026/03", end: "2026/12", region: "taitung",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川分署" },
    title: { en: "Shoreline-change monitoring and protection/adaptation strategies for general seawall areas and key settlements, Taitung (Dulanbi to south of the Taimali River mouth)",
             zh: "臺東一般性海堤區域及重要聚落海岸變遷監測調查及防護調適策略研擬（都蘭鼻岸段至南太麻里溪口岸段）" } },
  { type: "agency", start: "2025/05", end: "2026/12", region: "national",
    agency: { en: "WRA Water Resources Planning Branch", zh: "經濟部水利署水利規劃分署" },
    title: { en: "Improvement of coastal protection facilities and adaptation measures",
             zh: "海岸防護設施改善及調適措施研究" } },
  { type: "agency", start: "2025/05", end: "2026/12", region: "kinmen",
    agency: { en: "Kinmen County Government", zh: "金門縣政府" },
    title: { en: "Integrated coastal protection planning for Kinmen Island",
             zh: "金門本島海岸防護整合規劃" } },
  { type: "agency", start: "2025/05", end: "2026/11", region: "hualien",
    agency: { en: "Hualien County Government", zh: "花蓮縣政府" },
    title: { en: "Monitoring and protection strategies for the Xinshe coast, Hualien",
             zh: "花蓮縣新社海岸監測及防護策略研擬" } },
  { type: "agency", start: "2025/03", end: "2025/12", region: "taitung",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川分署" },
    title: { en: "Shoreline-change monitoring of general seawall areas and key settlements, Taitung (Sanjian Police Station to Shiyusan)",
             zh: "臺東海岸一般性海堤區域及重要聚落海岸變遷監測調查計畫（三間派出所至石雨傘）" } },
  { type: "agency", start: "2024/10", end: "2025/12", region: "hsinchu",
    agency: { en: "Hsinchu City Government", zh: "新竹市政府" },
    title: { en: "Hsinchu Fishery Harbor coastal monitoring and protection plan (2024)",
             zh: "113年新竹漁港海岸監測防護計畫" } },
  { type: "agency", start: "2024/06", end: "2025/12", region: "hsinchu",
    agency: { en: "Hsinchu City Government", zh: "新竹市政府" },
    title: { en: "Coastal topography monitoring survey, Hsinchu City",
             zh: "新竹市海岸地形監測調查計畫委託專業服務案" } },
  { type: "agency", start: "2024/05", end: "2024/12", region: "yilan",
    agency: { en: "Engineering consultancy (private sector)", zh: "維克科技工程顧問有限公司" },
    title: { en: "Harbor tranquility analysis, Su-ao Port, Yilan (consulting)",
             zh: "宜蘭縣蘇澳港－靜穩度分析諮詢顧問工作" } },
  { type: "agency", start: "2024/04", end: "2024/12", region: "national",
    agency: { en: "WRA Water Resources Planning Branch", zh: "經濟部水利署水利規劃分署" },
    title: { en: "Review of design tide levels and climate-change impacts",
             zh: "禦潮水位通盤檢討與氣候變遷衝擊研究" } },
  { type: "agency", start: "2024/03", end: "2024/12", region: "hualien",
    agency: { en: "WRA 9th River Management Branch", zh: "經濟部水利署第九河川分署" },
    title: { en: "Hualien coastal baseline monitoring and assessment of degraded segments with existing protection works (2/2)",
             zh: "花蓮海岸基本資料監測調查及既有海岸防護設施岸段環境劣化地區評估（2/2）" } },
  { type: "agency", start: "2024/02", end: "2024/12", region: "taitung",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川分署" },
    title: { en: "Shoreline-change monitoring of general seawall areas and key settlements, Taitung (Shiyusan to the Ba'ongong River mouth)",
             zh: "臺東海岸一般性海堤區域及重要聚落海岸變遷監測調查計畫（石雨傘至八嗡嗡溪口）" } },
  { type: "agency", start: "2023/05", end: "2024/12", region: "kinmen",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川局" },
    title: { en: "Kinmen coast assessment and planning (Guningtou to Mashan)",
             zh: "金門海岸（古寧頭至馬山）評估規劃計畫" } },
  { type: "agency", start: "2023/04", end: "2024/12", region: "kinmen",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川局" },
    title: { en: "Kinmen coast assessment and planning (Shuitou to Guningtou, and Dadan–Erdan islands)",
             zh: "金門海岸（水頭至古寧頭段及大二膽島）評估規劃計畫" } },
  { type: "agency", start: "2023/03", end: "2024/12", region: "taoyuan",
    agency: { en: "WRA 2nd River Management Branch", zh: "經濟部水利署第二河川局" },
    title: { en: "Risk assessment of general seawalls, Taoyuan City",
             zh: "桃園市一般性海堤風險評估" } },
  { type: "agency", start: "2023/02", end: "2024/12", region: "green",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川局" },
    title: { en: "Risk assessment and response strategies for general seawalls on Green Island and Orchid Island",
             zh: "綠島與蘭嶼地區一般性海堤岸段風險評估與因應策略" } },
  { type: "agency", start: "2023/02", end: "2023/12", region: "hualien",
    agency: { en: "WRA 9th River Management Branch", zh: "經濟部水利署第九河川局" },
    title: { en: "Hualien coastal baseline monitoring and assessment of degraded segments with existing protection works (1/2)",
             zh: "花蓮海岸基本資料監測調查及既有海岸防護設施岸段環境劣化地區評估（1/2）" } },
  { type: "agency", start: "2022/08", end: "2023/08", region: "taitung",
    agency: { en: "East Coast National Scenic Area Administration, Tourism Bureau", zh: "交通部觀光局東部海岸國家風景區管理處" },
    title: { en: "Sea-cliff erosion control and improvement planning, Jialulan Recreation Area, Taitung",
             zh: "臺東加路蘭遊憩區海崖侵蝕防治措施及改善研究規劃委託技術服務" } },
  { type: "agency", start: "2022/02", end: "2022/12", region: "kinmen",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川局" },
    title: { en: "Risk assessment of general seawalls, Kinmen County (2022)",
             zh: "111年度金門縣一般性海堤風險評估" } },
  { type: "agency", start: "2022/02", end: "2022/12", region: "taitung",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川局" },
    title: { en: "Risk assessment and response strategies for general seawall segments, Taitung (2/2)",
             zh: "臺東一般性海堤岸段風險評估與因應策略（2/2）" } },
  { type: "agency", start: "2022/01", end: "2022/12", region: "hualien",
    agency: { en: "WRA 9th River Management Branch", zh: "經濟部水利署第九河川局" },
    title: { en: "Risk assessment of general seawalls, Hualien County (2/2)",
             zh: "111年度花蓮縣一般性海堤風險評估（2/2）" } },
  { type: "agency", start: "2021/06", end: "2022/07", region: "kinmen",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川局" },
    title: { en: "Monitoring and erosion–accretion assessment, western Lieyu coast, Kinmen",
             zh: "金門海岸（烈嶼鄉西側）監測及侵淤評估規劃計畫" } },
  { type: "agency", start: "2021/05", end: "2022/12", region: "hsinchu",
    agency: { en: "Hsinchu City Government", zh: "新竹市政府" },
    title: { en: "Hsinchu Fishery Harbor coastal monitoring and protection plan (2021)",
             zh: "110年新竹漁港海岸監測防護計畫" } },
  { type: "agency", start: "2021/03", end: "2021/12", region: "national",
    agency: { en: "National Academy of Marine Research", zh: "國家海洋研究院" },
    title: { en: "National survey and safety assessment of beaches and fishing spots",
             zh: "全國海灘及釣點環境調查與安全評估作業" } },
  { type: "agency", start: "2021/03", end: "2021/12", region: "taoyuan",
    agency: { en: "WRA 2nd River Management Branch", zh: "經濟部水利署第二河川局" },
    title: { en: "Shoreline-change monitoring of general seawall areas and key settlements, Taoyuan (2/2)",
             zh: "桃園一般性海堤區域及重要聚落海岸變遷監測調查計畫（2/2）" } },
  { type: "agency", start: "2021/03", end: "2021/12", region: "hualien",
    agency: { en: "WRA 9th River Management Branch", zh: "經濟部水利署第九河川局" },
    title: { en: "Risk assessment of general seawalls, Hualien County (1/2)",
             zh: "110年度花蓮縣一般性海堤風險評估（1/2）" } },
  { type: "agency", start: "2021/03", end: "2021/12", region: "taitung",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川局" },
    title: { en: "Shoreline-change monitoring of general seawall areas and key settlements, Taitung (Fugang to the Lijia River mouth) (2/2)",
             zh: "臺東一般性海堤區域及重要聚落海岸變遷監測調查計畫（富岡至利嘉溪口）（2/2）" } },
  { type: "agency", start: "2021/01", end: "2021/12", region: "taitung",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川局" },
    title: { en: "Risk assessment and response strategies for general seawall segments, Taitung (1/2)",
             zh: "臺東一般性海堤岸段風險評估與因應策略（1/2）" } },
  { type: "agency", start: "2020/08", end: "2020/12", region: "yilan",
    agency: { en: "National Science and Technology Center for Disaster Reduction", zh: "國家災害防救科技中心" },
    title: { en: "Historical analysis of zero-datum water-level change along the Yilan coast",
             zh: "宜蘭海岸線零米水位變化歷年分析" } },
  { type: "agency", start: "2020/05", end: "2020/12", region: "national",
    agency: { en: "WRA Water Resources Planning Institute", zh: "經濟部水利署水利規劃試驗所" },
    title: { en: "Coastal hazard risk and resilience of disaster buffer zones on offshore islands",
             zh: "離島海岸災害風險與防災緩衝區韌性探討" } },
  { type: "agency", start: "2020/03", end: "2020/12", region: "taoyuan",
    agency: { en: "WRA 2nd River Management Branch", zh: "經濟部水利署第二河川局" },
    title: { en: "Shoreline-change monitoring of general seawall areas and key settlements, Taoyuan (1/2)",
             zh: "桃園一般性海堤區域及重要聚落海岸變遷監測調查計畫（1/2）" } },
  { type: "agency", start: "2020/02", end: "2020/12", region: "taitung",
    agency: { en: "WRA 8th River Management Branch", zh: "經濟部水利署第八河川局" },
    title: { en: "Shoreline-change monitoring of general seawall areas and key settlements, Taitung (Fugang to the Lijia River mouth) (1/2)",
             zh: "臺東一般性海堤區域及重要聚落海岸變遷監測調查計畫（富岡至利嘉溪口）（1/2）" } },

  /* ---------- NSTC (formerly MOST) research grants ---------- */
  { type: "nstc", start: "2025/08", end: "", role: "Co-PI", region: "national",
    agency: { en: "NSTC", zh: "國科會" },
    title: { en: "AI-based disaster-prevention technology for slope hazards (I)",
             zh: "人工智慧防災技術應用於坡地災害之研究(I)" } },
  { type: "nstc", start: "2024/08", end: "2025/07", role: "PI", region: "national",
    agency: { en: "NSTC", zh: "國科會" },
    title: { en: "Mechanisms of coastal slope failure and sea-cliff foreshore erosion under different environmental settings, and smart adaptation and resilience strategies (Subproject 3) (III)",
             zh: "人工智慧防災技術應用於坡地災害之研究－環境差異性對臨海邊坡崩坍與海崖前灘侵蝕災害發生機制研析與智慧防災調適韌性策略研究（子計畫三）(III)" } },
  { type: "nstc", start: "2023/08", end: "2024/07", role: "PI", region: "national",
    agency: { en: "NSTC", zh: "國科會" },
    title: { en: "Slope-hazard risk assessment and smart disaster-prevention strategies for offshore-island coasts (Subproject 3) (II)",
             zh: "坡地災害風險評估及智慧防災－離島海岸地區邊坡災害風險評估與智慧防災策略研究（子計畫三）(II)" } },
  { type: "nstc", start: "2022/08", end: "2023/07", role: "PI", region: "national",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Slope-hazard risk assessment and smart disaster-prevention strategies for offshore-island coasts (Subproject 3) (I)",
             zh: "坡地災害風險評估及智慧防災－離島海岸地區邊坡災害風險評估與智慧防災策略研究（子計畫三）(I)" } },
  { type: "nstc", start: "2020/08", end: "2021/07", role: "PI", region: "national",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Coastal erosion risk assessment and strategies for strengthening adaptive resilience (Subproject 1), under Compound hazard risk assessment and integrated mitigation strategies for coastal areas under climate change (I)",
             zh: "氣候變遷下海岸地區之複合性災害風險評估及整合性避災與減災策略研究－海岸侵蝕災害風險評估及強化韌性調適能力策略研究（子計畫一）(I)" } },
  { type: "nstc", start: "2020", end: "", role: "Co-PI", region: "keelung",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Integration of central and local disaster-response information: Keelung City (3/3)",
             zh: "中央與基隆市防救災情資整合與技術研發－中央與地方防救災情資整合研究計畫－基隆市(3/3)" } },
  { type: "nstc", start: "2019", end: "", role: "PI", region: "national",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Coastal erosion risk assessment and management for developed coastal cities and settlements",
             zh: "海岸地區都市與聚落受氣候變遷之風險評估及整合管理與調適－海岸開發城市聚落之海岸侵蝕風險評估管理" } },
  { type: "nstc", start: "2019", end: "", role: "Co-PI", region: "national",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Integrated climate-change risk assessment of coastal areas for national land management and adaptation",
             zh: "海岸地區都市與聚落受氣候變遷之風險評估及整合管理與調適－海岸地區受氣候變遷之整合性風險評估於國土管理利用與調適之研究" } },
  { type: "nstc", start: "2019", end: "", role: "Co-PI", region: "keelung",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Integration of central and local disaster-response information: Keelung City (2/3)",
             zh: "中央與基隆市防救災情資整合與技術研發－中央與地方防救災情資整合研究計畫－基隆市(2/3)" } },
  { type: "nstc", start: "2018", end: "", role: "Co-PI", region: "keelung",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Integration of central and local disaster-response information: Keelung City (1/3)",
             zh: "中央與基隆市防救災情資整合與技術研發－中央與地方防救災情資整合研究計畫－基隆市(1/3)" } },
  { type: "nstc", start: "2017", end: "", role: "PI", region: "national",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Coastal erosion risk classification and compensation strategies for Taiwan",
             zh: "海岸開發利用與國土保護及環境風險評估－台灣海岸侵蝕風險分級及因應補償策略研究" } },
  { type: "nstc", start: "2016", end: "", role: "PI", region: "national",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Coastal erosion risk classification and compensation strategies for Taiwan (I)",
             zh: "海岸開發利用與國土保護及環境風險評估－台灣海岸侵蝕風險分級及因應補償策略研究(I)" } },
  { type: "nstc", start: "2015", end: "", role: "PI", region: "national",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Design standards for sustainable coastal protection works and non-structural measures (II)",
             zh: "氣候變遷下海岸地區發展與海洋變遷互動之研究－永續性海岸防護工程標準訂定與非工程措施(II)" } },
  { type: "nstc", start: "2014", end: "", role: "PI", region: "national",
    agency: { en: "MOST", zh: "科技部" },
    title: { en: "Design standards for sustainable coastal protection works and non-structural measures (I)",
             zh: "氣候變遷下海岸地區發展與海洋變遷互動之研究－永續性海岸防護工程標準訂定與非工程措施(I)" } },
  { type: "nstc", start: "2013", end: "", role: "Co-PI", region: "national",
    agency: { en: "NSC · National Energy Program", zh: "國科會・能源國家型科技計畫" },
    title: { en: "Marine-works planning, design and construction specifications for offshore wind farms (I)",
             zh: "離岸式風力發電海事工程規劃設計與施工規範之研究(I)" } },
  { type: "nstc", start: "2012", end: "", role: "PI", region: "national",
    agency: { en: "NSC · New investigator grant", zh: "國科會・新進人員研究計畫" },
    title: { en: "Effects of river sediment supply on coastal morphological change",
             zh: "河川輸沙對海岸地形變遷之影響" } }
];
